- name: adding oracle java repository
  shell: add-apt-repository -y ppa:webupd8team/java

- name: adding dse repo
  shell: echo "deb http://datastaxrepo_gmail.com:utJVKEg4lKeaWTX@debian.datastax.com/enterprise stable main" | sudo tee -a /etc/apt/sources.list.d/datastax.sources.list

- name: adding dse repo key
  shell: curl -L https://debian.datastax.com/debian/repo_key | sudo apt-key add -

- name: updating machine
  shell: apt-get update
